### ISSUE TITLE
sendMessage方法 transactionSynchronize 之前没有开启事务 会报错吧！

### ISSUE THREAD

**Issue by dennislee414** [zjpjohn/ReliableMeageSystem#5]
/**
     * 发送消息
     *
     * @param data
     */
    public void sendMessage(Map<String, String> data) {
        Preconditions.checkArgument(data != null && data.size() != 0, "message must not be empty...");
        transactionSynchronize();
        QMessage message = convertMessage(data);
        int result = qMessageService.addQMessage(message);
        if (result != 0) {
            MessageHolder.set(message.getMessageId());
        }
    }

**Comment by chenxuezhou** [comment]
代码好像没有改，为啥没开启之前会报错，看了下代码这是本地插入QMessag消息？？
